### ISSUE TITLE
How to enable?

### ISSUE THREAD

**Issue by PatrickHeneise** [capaj/vscode-standardjs-snippets#1]
I'm working with the atom snippets plugin for a while. After installing and restarting, I type `cl` or `ase`, I get vscode completes, not standard snippets. `ase => case` / `cl => class`

How do I enable this plugin / how does it work?

**Comment by capaj** [comment]
@PatrickHeneise this is probably due to vscode not prioritizing the snippets. Try: 
```
"editor.snippetSuggestions": "top",
```

feel free to reopen the issue if this does not work for you.

**Comment by PatrickHeneise** [comment]
ok, thanks!
