### ISSUE TITLE
console.log snippets has change?

### ISSUE THREAD

**Issue by bestvow** [capaj/vscode-standardjs-snippets#11]
![snipaste_2017-12-23_21-55-22](https://user-images.githubusercontent.com/24888709/34320075-28fc5cbc-e82c-11e7-8d39-1074a9e5ebf7.png)
![snipaste_2017-12-23_21-54-33](https://user-images.githubusercontent.com/24888709/34320076-2dcca9b8-e82c-11e7-909d-713071969c92.png)
![snipaste_2017-12-23_21-54-47](https://user-images.githubusercontent.com/24888709/34320077-33105ed8-e82c-11e7-9595-ebe3d1f0be59.png)
![snipaste_2017-12-23_22-02-25](https://user-images.githubusercontent.com/24888709/34320123-1a21eaee-e82d-11e7-8c67-23dc394b6bd6.png)
If the snippets shortcuts key has change would you like to fix the introduce

**Comment by capaj** [comment]
fixed in 0.7.5 which was just released, sorry for your trouble
