### ISSUE TITLE
class constructor space-before-function-paren and semi

### ISSUE THREAD

**Issue by DaxChen** [capaj/vscode-standardjs-snippets#4]
Hi, thanks for this awesome extension.

I found that `cs` and `csx` has some styling issue that standardjs will complain about...

1. The `constructor` and `()` is missing a space.
2. The `super(arguments);` has an extra semicolon.

**Comment by capaj** [comment]
@DaxChen published as 0.5.0

**Comment by DaxChen** [comment]
wow that was super fast!
Thanks!
👍
