### ISSUE TITLE
Can it be customized? Or console.log supercharged

### ISSUE THREAD

**Issue by bernardoadc** [capaj/vscode-standardjs-snippets#9]
I want to have `cl` become `console.log('${0}:', ${0})` with double cursor activated. 

1) Is there a chance to do so
2) can you put it officially
3) (how) can I hack the extension for my use only

**Comment by capaj** [comment]
you can just override any of the snippets with 
![screenshot from 2017-12-19 04-02-12](https://user-images.githubusercontent.com/1305378/34138849-04c8924c-e472-11e7-8721-3a9bc6da3813.png)

It's a good idea to have that as official version! Will include in the next release

**Comment by capaj** [comment]
this snippet is now under `cv`, not as `cl`. Some people use console.log plainly to log a single thing

**Comment by bernardoadc** [comment]
Yes, it's a good choice as well. I've seen myself using it and deleting the expression part, for logging just a string (so I would change `cl` anyway to `console.log('${0}')` and not `console.log(${0})`, since logging expressions alone would be bad practice and should always be identified)
